###################################
##### Bungee Chat Plus Config #####
###################################
# This is the line for formatting chat messages
# Usable variables are: %player%  %message% %prefix% %suffix% %type% %forced%
# %type% and %forced% can be configured further using varGlobalChat etc.
chatFormat: "&a[&9%type%%forced%&a] &9%server% %prefix% %tabName%&a:&r%suffix% %message%"
# If connection with the bukkitbridge fails, it will still send the message with the backup format.
backupChatFormat: "<%player%>&r %message%"

varGlobalChat: "Global"
varLocalChat: "Local"
varForcedGlobal: "-Forced"
varNotForced: ""
localChatMessage: "&7You are now listening to local chat."
globalChatMessage: "&7You are now listening to global chat."
toggleChatCommandEnabled: true
toggleChatCommandAliases: ['togglechat', 'chattoggle']
globalChatCommandEnabled: false
globalChatCommandAliases: ['global', 'g']
localChatCommandEnabled: false
localChatCommandAliases: ['local', 'l']

###################################
#####    Private Messaging    #####
###################################
pmEnabled: true
pmSend: "&b[suggest=/w %target% ]You -> %target%[/suggest]&f > [i]%message%[/i]"
pmReceive: "&b[suggest=/w %player% ]%player% -> me[/suggest] &f> [i]%message%[/i]"
pmUnknownTarget: "&c%target% is not on the server"
pmPlaySound: true
pmSound: ORB_PICKUP
pmCommandAliases: ['w', 'msg', 'message', 'tell', 'whisper', 'pm']
pmReplyCommandAliases: ['reply', 'r']
# Conversations - PMs but with no other chat
pmConversationCommandAliases: ['chat', 'conversation']
pmConversationStartMessage: "&aYou started a conversation with %target%. All your chat messages will go directly to %target%."
pmConversationEndMessage: "&cYour conversation with %target% is over. Chat works as normal again."

###################################
#####    Mentioning Players   #####
###################################
enableTaggingPlayers: true
taggedPlayer: "[color=gold][suggest=/w ${name}]@${name}[/suggest][/color]"
playSoundToTaggedPlayer: true
playerTaggedSound: ORB_PICKUP

###################################
#####      Player Muting      #####
###################################
muteEnabled: true
muteMessage: "&cYou have been muted for %reason% until %duration%"
mutePardonMessage: "&cYou have been unmuted"
muteDenyMessage: "&cYou are muted for %reason% until %duration%. for further assistance pm a Moderator."
muteSuccess: "&7%target% has been muted for %reason% until %duration%"
muteUnmuted: "&7%target% has been unmuted"
muteMuteFail: "&7%target% is already muted for %reason% until %duration%"
muteUnmuteFail: "&7%target% is not muted"
muteCommandAliases: ['mute', 'bungeemute']
muteUnmuteCommandAliases: ['unmute', 'bungeeunmute']
muteListCommandAliases: ['mutelist', 'bungeemutelist', 'listmuted', 'bungeelistmuted']

###################################
#####      Player Ignore      #####
###################################
ignoreEnabled: true
ignored: "&c%target% has ignored you"
ignoreSuccess: "&7You ignored %target%"
ignoreUnignore: "&7You no longer ignore %target%"
ignoreCommandAliases: ['ignore', 'ignoreplayer']

###################################
#####        Anti-Spam        #####
###################################
antiSpamEnabled: true
antiSpamMuteTime: 60
antiSpamDenyMessage: "&cYou have sent to many messages. You must wait 1 minute before sending messages again."

antiCapsEnabled: true
antiCapsMinChatLength: 3
antiCapsActivationPercentage: 50
antiCapsAutoLowercase: true
antiCapsMessage: "&bPlease refrain from using caps in chat"

antiSwearEnabled: true
antiSwearMessage: "&bPlease refrain from swearing in chat"
antiSwearList: ['fuck', 'shit', 'damn']

###################################
#####           Misc          #####
###################################
# If enabled chat messaged are written into logs in the BungeeChatPlus directory
logChat: true
logCommands: true
consoleName: "&4CONSOLE"
bcpCommandAliases: ['bcp', 'bungeechatplus']
reloadCommandAliases: ['bcpreload', 'bungeechatplusreload']
unknownTarget: "&7%target% is not on the server"
internalError: "&cAn internal error occurred while processing your chat message."
alwaysGlobalChat: true
allowBBCodeInVariables: false
excludeServers: []
versionDontTouch:
  seriouslyThisWillEraseYourConfig: '1.8'

###################################
#####          Regex          #####
###################################
regex:
# make any pasted links clickable for convenience
    - search: '(?<link>(?:(https?)://)?([-\w_\.]{2,}\.[a-z]{2,4})(/\S*)?)'
      replace: "[url]${link}[/url]"
# shows link target in tooltip for security reasons (only if link target differs from shown text)
    - search: '(?i)\[(?:url|command)=(?<cmd>(?:(?:[^]\[]*)\[(?:[^]\[]*)\])*(?:[^]\[]*))\]'
      replace: "[hover=&b${cmd}]$0"
    - search: '(?i)\[/(?:url|command)\]'
      replace: "$0[/hover]"
# if players write commands in chat like ./command, make them clickable + remove the dot
    - search: '(?i)^\.(?<cmd>/.{2,})'
      replace: "[suggest]${cmd}[/suggest]"
# some smileys
    - search: '--->'
      replace: "\u21DB"
    - search: '<---'
      replace: "\u21DA"
    - search: '-->'
      replace: "\u21D2"
    - search: '<--'
      replace: "\u21D0"
    - search: '->'
      replace: "\u2192"
    - search: '<-'
      replace: "\u2190"
    - search: '\(o\)|\(O\)|\(time\)'
      replace: "\u231A"
    - search: '\(rain\)'
      replace: "\u2602"
    - search: '\(sun\)'
      replace: "\u2600"
    - search: '<3'
      replace: "\u2764"
# underline clickable things
    - search: '(?i)(?=(\[(?:url|command|suggest)(?:=(?<cmd>(?:(?:[^]\[]*)\[(?:[^]\[]*)\])*(?:[^]\[]*)))?\]))'
      replace: "[u]"
    - search: '(?i)\[/(?:url|command|suggest)\]'
      replace: "$0[/u]"